version: '3.8'
services:
  backend:
    build:
       context: .
       dockerfile: ./backend.Dockerfile
    container_name: backend
#    ports:
#       - "8080:8080"
    networks:
      - backend
    command: java -jar /app/target/demo-0.0.1-SNAPSHOT.jar

  frontend: 
    build:
       context: .
       dockerfile: ./frontend.Dockerfile
    container_name: frontend
#   ports:
#      - "8000:4200"
    networks:
      - backend
    command: npm start

  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    container_name: httpredirect
    ports:
      - 80:80
      - 443:443
    networks: 
      - frontend
      - backend

networks:
  frontend:
  backend: 
